#!/bin/bash
cd /tmp/rom # Depends on where source got synced
rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur

# Normal build steps
. build/envsetup.sh
lunch nad_violet-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	mka api-stubs-docs -j20
	mka system-api-stubs-docs -j20
	mka test-api-stubs-docs -j20
}

make_rom(){
	mka nad -j20
	zip=$(up out/target/product/violet/*zip)
	echo " "
	echo "$zip"
}

make_metalava
make_rom &
kill "$!"
