#!/bin/bash
cd /tmp/rom # Depends on where source got synced
rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur

# Normal build steps
. build/envsetup.sh
lunch lighthouse_miatoll-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	mka api-stubs-docs -j26
	mka system-api-stubs-docs -j26
	mka test-api-stubs-docs -j26
}

make_rom(){
	make bacon -j26
	zip=$(up out/target/product/miatoll/*zip)
	echo " "
	echo "$zip"
}

make_metalava
make_rom
sudo apt install tmate && ssh-keygen && tmate
