#!/bin/bash

url=https://ghostmirror.hitesh920.workers.dev/gay16.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf gay16.tar.gz
echo "unzip done"
find gay16.tar.gz -delete
