#!/bin/bash

url=https://ghostmirror.hitesh920.workers.dev/pero12.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf pero12.tar.gz
echo "unzip done"
find pero12.tar.gz -delete
