#!/bin/bash
sudo apt install wget
MANIFEST=git://github.com/NusantaraProject-ROM/android_manifest.git
BRANCH=11

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name "Brucetech"
git config --global user.email jashvakharia@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j16

git clone --depth=1 --single-branch https://github.com/NusantaraROM-Devices/device_xiaomi_violet.git -b 11 device/xiaomi/violet
git clone --depth=1 --single-branch https://github.com/NusantaraROM-Devices/vendor_xiaomi_violet.git -b 11 vendor/xiaomi/violet
git clone --depth=1 --single-branch https://github.com/NusantaraROM-Devices/android_kernel_xiaomi_violet.git kernel/xiaomi/violet --depth=1
