#!/bin/bash
sudo apt install wget
MANIFEST=git://github.com/lighthouse-os/manifest.git
BRANCH=raft

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name "Box In A Box"
git config --global user.email evanferrao@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j26

git clone https://github.com/ArrowOS-Devices/android_device_xiaomi_miatoll.git -b arrow-11.0 device/xiaomi/miatoll
git clone https://github.com/ArrowOS-Devices/android_device_xiaomi_sm6250-common.git -b arrow-11.0 device/xiaomi/sm6250-common
git clone https://github.com/ArrowOS-Devices/android_vendor_xiaomi_miatoll.git -b arrow-11.0 vendor/xiaomi/miatoll
git clone --depth=1 --single-branch https://github.com/ArrowOS-Devices/android_kernel_xiaomi_sm6250.git -b arrow-11.0 kernel/xiaomi/sm625
git clone https://github.com/ArrowOS-Devices/android_vendor_xiaomi_sm6250-common.git -b arrow-11.0 vendor/xiaomi/sm6250-common
cd device/xiaomi/sm6250-common && mv arrow.dependencies lighthouse.dependencies && cd ../../..
cd device/xiaomi/miatoll && mv arrow.dependencies lighthouse.dependencies && rm -rf AndroidProducts.mk arrow_miatoll.mk && wget https://ghostmirror.hitesh920.workers.dev/lighthouse_miatoll.mk && wget https://ghostmirror.hitesh920.workers.dev/AndroidProducts.mk && cd ../../..
